# Site settings
title: Neobrutal
email: luis.pacheco@neobrutal.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook: https://www.facebook.com/neobrutalstudio
linkedin: https://www.linkedin.com/company/79764820
instagram: https://www.instagram.com/neobrutalstudio/ 

# Build settings
markdown: kramdown
